default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 197519
  host: localhost
  port: 5432

development:
  <<: *default
  database: camera_app_development

test:
  <<: *default
  database: camera_app_test

